'use client';

import React from 'react';

/* ────────────────────────────────────────────────────────────
   Nailart AI — Hero visual
   Pure SVG (no icons): an AI-generated YouTube thumbnail floating
   above a stack of result variants.
   ──────────────────────────────────────────────────────────── */
export function ThumbnailShowcase() {
  return (
    <div
      style={{
        width: '100%',
        maxWidth: 500,
        position: 'relative',
        filter: 'drop-shadow(0 32px 64px rgba(0,0,0,0.55))',
      }}
    >
      <style>{`
        @keyframes na-thumb-float {
          0%, 100% { transform: translateY(0px) rotate(-1deg); }
          50%      { transform: translateY(-16px) rotate(-1deg); }
        }
        .na-thumb-wrap {
          animation: na-thumb-float 5s ease-in-out infinite;
          transform-origin: center;
        }
      `}</style>

      <svg
        viewBox="0 0 500 370"
        xmlns="http://www.w3.org/2000/svg"
        width="100%"
        height="auto"
        aria-label="A YouTube thumbnail generated by Nailart AI"
        role="img"
      >
        <defs>
          {/* Card gradients */}
          <linearGradient id="ng-g-back1" x1="0%" y1="0%" x2="100%" y2="100%">
            <stop offset="0%" stopColor="#1e3a8a" />
            <stop offset="100%" stopColor="#5b21b6" />
          </linearGradient>
          <linearGradient id="ng-g-back2" x1="0%" y1="0%" x2="100%" y2="100%">
            <stop offset="0%" stopColor="#9d174d" />
            <stop offset="100%" stopColor="#c2410c" />
          </linearGradient>
          <linearGradient id="ng-g-main" x1="0%" y1="0%" x2="100%" y2="100%">
            <stop offset="0%" stopColor="#4c1d95" />
            <stop offset="40%" stopColor="#86198f" />
            <stop offset="100%" stopColor="#be123c" />
          </linearGradient>
          <linearGradient id="ng-g-badge" x1="0%" y1="0%" x2="100%" y2="0%">
            <stop offset="0%" stopColor="#7c3aed" />
            <stop offset="100%" stopColor="#db2777" />
          </linearGradient>
          <linearGradient id="ng-g-overlay" x1="0%" y1="0%" x2="0%" y2="100%">
            <stop offset="0%" stopColor="transparent" />
            <stop offset="100%" stopColor="rgba(0,0,0,0.7)" />
          </linearGradient>
          <linearGradient id="ng-g-face" x1="0%" y1="0%" x2="100%" y2="100%">
            <stop offset="0%" stopColor="#fbbf24" />
            <stop offset="100%" stopColor="#f97316" />
          </linearGradient>

          {/* Drop shadow */}
          <filter id="ng-shadow" x="-25%" y="-25%" width="150%" height="150%">
            <feDropShadow dx="0" dy="20" stdDeviation="20" floodColor="#000" floodOpacity="0.55" />
          </filter>

          {/* Soft glow */}
          <filter id="ng-glow" x="-30%" y="-30%" width="160%" height="160%">
            <feGaussianBlur stdDeviation="4" result="blur" />
            <feMerge>
              <feMergeNode in="blur" />
              <feMergeNode in="SourceGraphic" />
            </feMerge>
          </filter>

          {/* Clip paths */}
          <clipPath id="ng-clip-back1">
            <rect x="20" y="95" width="310" height="175" rx="12" />
          </clipPath>
          <clipPath id="ng-clip-back2">
            <rect x="170" y="110" width="310" height="175" rx="12" />
          </clipPath>
          <clipPath id="ng-clip-main">
            <rect x="60" y="72" width="380" height="214" rx="14" />
          </clipPath>
        </defs>

        {/* ── Back card — left ── */}
        <g transform="rotate(-9, 175, 182)" opacity="0.6">
          <rect x="20" y="95" width="310" height="175" rx="12" fill="url(#ng-g-back1)" />
          <g clipPath="url(#ng-clip-back1)">
            {/* Decorative circles */}
            <circle cx="90" cy="155" r="55" fill="rgba(255,255,255,0.07)" />
            <circle cx="280" cy="120" r="40" fill="rgba(255,255,255,0.05)" />
            {/* Bottom bar */}
            <rect x="20" y="225" width="310" height="45" fill="rgba(0,0,0,0.55)" />
            <rect x="35" y="234" width="170" height="10" rx="5" fill="rgba(255,255,255,0.75)" />
            <rect x="35" y="249" width="110" height="7" rx="3" fill="rgba(255,255,255,0.45)" />
          </g>
          <rect x="20" y="95" width="310" height="175" rx="12" fill="none" stroke="rgba(255,255,255,0.14)" strokeWidth="1" />
        </g>

        {/* ── Back card — right ── */}
        <g transform="rotate(7, 325, 197)" opacity="0.6">
          <rect x="170" y="110" width="310" height="175" rx="12" fill="url(#ng-g-back2)" />
          <g clipPath="url(#ng-clip-back2)">
            <circle cx="260" cy="160" r="60" fill="rgba(255,255,255,0.06)" />
            <circle cx="440" cy="130" r="35" fill="rgba(255,255,255,0.05)" />
            <rect x="170" y="240" width="310" height="45" fill="rgba(0,0,0,0.55)" />
            <rect x="185" y="249" width="170" height="10" rx="5" fill="rgba(255,255,255,0.75)" />
            <rect x="185" y="264" width="110" height="7" rx="3" fill="rgba(255,255,255,0.45)" />
          </g>
          <rect x="170" y="110" width="310" height="175" rx="12" fill="none" stroke="rgba(255,255,255,0.14)" strokeWidth="1" />
        </g>

        {/* ── Main card (front, floating) ── */}
        <g className="na-thumb-wrap" filter="url(#ng-shadow)">
          {/* Background */}
          <rect x="60" y="72" width="380" height="214" rx="14" fill="url(#ng-g-main)" />

          {/* Thumbnail content (clipped inside card) */}
          <g clipPath="url(#ng-clip-main)">
            {/* Abstract light blobs */}
            <circle cx="170" cy="155" r="95" fill="rgba(255,255,255,0.06)" />
            <circle cx="360" cy="120" r="70" fill="rgba(255,255,255,0.05)" />
            <ellipse cx="420" cy="180" rx="65" ry="90" fill="rgba(255,255,255,0.04)" transform="rotate(-25, 420, 180)" />

            {/* Illustrated "person" silhouette — SVG paths only, no icons */}
            {/* Head */}
            <circle cx="170" cy="140" r="36" fill="url(#ng-g-face)" opacity="0.9" />
            {/* Body */}
            <path
              d="M138 170 Q145 195 170 205 Q195 195 202 170 Q195 165 170 168 Q145 165 138 170Z"
              fill="url(#ng-g-face)"
              opacity="0.75"
            />
            {/* Shock/expression lines */}
            <path d="M118 110 L128 118" stroke="rgba(255,220,50,0.8)" strokeWidth="2.5" strokeLinecap="round" />
            <path d="M112 125 L124 127" stroke="rgba(255,220,50,0.8)" strokeWidth="2.5" strokeLinecap="round" />
            <path d="M120 140 L130 135" stroke="rgba(255,220,50,0.8)" strokeWidth="2.5" strokeLinecap="round" />

            {/* Bold YouTube-style title text */}
            <text
              x="282"
              y="138"
              fontSize="26"
              fontWeight="900"
              fill="white"
              textAnchor="middle"
              fontFamily="system-ui, -apple-system, sans-serif"
              style={{ textShadow: '0 2px 12px rgba(0,0,0,0.7)' }}
            >
              10 MILLION SUBS
            </text>
            <text
              x="282"
              y="168"
              fontSize="18"
              fontWeight="800"
              fill="#fbbf24"
              textAnchor="middle"
              fontFamily="system-ui, -apple-system, sans-serif"
            >
              THE SECRET, REVEALED
            </text>

            {/* Gradient overlay at bottom */}
            <rect x="60" y="180" width="380" height="106" fill="url(#ng-g-overlay)" />

            {/* Bottom info bar */}
            {/* Channel avatar — letter N in circle */}
            <circle cx="86" cy="264" r="15" fill="rgba(124,58,237,0.95)" />
            <text
              x="86"
              y="269"
              fontSize="13"
              fontWeight="700"
              fill="white"
              textAnchor="middle"
              fontFamily="system-ui, -apple-system, sans-serif"
            >
              N
            </text>
            {/* Channel name */}
            <text x="108" y="258" fontSize="10" fill="rgba(255,255,255,0.88)" fontFamily="system-ui, -apple-system, sans-serif" fontWeight="600">
              Nailart AI Channel
            </text>
            <text x="108" y="273" fontSize="9" fill="rgba(255,255,255,0.5)" fontFamily="system-ui, -apple-system, sans-serif">
              2.3M views · 1 day ago
            </text>

            {/* Duration badge */}
            <rect x="392" y="253" width="40" height="18" rx="3" fill="rgba(0,0,0,0.85)" />
            <text x="412" y="265" fontSize="8.5" fill="white" textAnchor="middle" fontFamily="system-ui, -apple-system, sans-serif">
              12:34
            </text>
          </g>

          {/* Card border */}
          <rect x="60" y="72" width="380" height="214" rx="14" fill="none" stroke="rgba(255,255,255,0.22)" strokeWidth="1.5" />
        </g>

        {/* ── "AI Generated" pill badge ── */}
        <g filter="url(#ng-glow)">
          <rect x="62" y="294" width="155" height="34" rx="17" fill="url(#ng-g-badge)" />
          {/* Sparkle — 4-pointed star (SVG path) */}
          <path
            d="M86 311 L88.5 304 L91 311 L98 311 L92.5 315.5 L94.5 322.5 L88.5 318.5 L82.5 322.5 L84.5 315.5 L79 311 Z"
            fill="white"
            opacity="0.95"
          />
          <text
            x="104"
            y="316"
            fontSize="12"
            fill="white"
            fontFamily="system-ui, -apple-system, sans-serif"
            fontWeight="600"
          >
            AI Generated
          </text>
        </g>

        {/* ── CTR stats badge ── */}
        <rect x="228" y="294" width="110" height="34" rx="17" fill="rgba(16,185,129,0.92)" stroke="rgba(255,255,255,0.2)" strokeWidth="1" />
        {/* Up-arrow chevron (SVG path) */}
        <path d="M246 315 L250 309 L254 315" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" fill="none" />
        <text
          x="279"
          y="316"
          fontSize="12"
          fill="white"
          textAnchor="middle"
          fontFamily="system-ui, -apple-system, sans-serif"
          fontWeight="700"
        >
          CTR 12.4%
        </text>

        {/* ── "Powered by" label ── */}
        <rect x="350" y="294" width="92" height="34" rx="17" fill="rgba(255,255,255,0.1)" stroke="rgba(255,255,255,0.18)" strokeWidth="1" />
        <text
          x="396"
          y="316"
          fontSize="10.5"
          fill="rgba(255,255,255,0.8)"
          textAnchor="middle"
          fontFamily="system-ui, -apple-system, sans-serif"
          fontWeight="500"
        >
          Nailart AI
        </text>

        {/* ── Animated sparkle particles ── */}

        {/* Circle sparkle — top left */}
        <circle cx="42" cy="108" r="5" fill="rgba(167,139,250,0.85)">
          <animate attributeName="opacity" values="0.85;0.2;0.85" dur="2.4s" repeatCount="indefinite" />
          <animate attributeName="r" values="5;7;5" dur="2.4s" repeatCount="indefinite" />
        </circle>

        {/* Circle sparkle — right edge */}
        <circle cx="472" cy="100" r="4" fill="rgba(244,114,182,0.85)">
          <animate attributeName="opacity" values="0.85;0.15;0.85" dur="1.9s" begin="0.6s" repeatCount="indefinite" />
          <animate attributeName="r" values="4;6.5;4" dur="1.9s" begin="0.6s" repeatCount="indefinite" />
        </circle>

        {/* Circle sparkle — bottom right */}
        <circle cx="478" cy="285" r="5" fill="rgba(96,165,250,0.8)">
          <animate attributeName="opacity" values="0.8;0.2;0.8" dur="3.1s" begin="1s" repeatCount="indefinite" />
        </circle>

        {/* Circle sparkle — bottom left */}
        <circle cx="22" cy="278" r="3.5" fill="rgba(251,191,36,0.85)">
          <animate attributeName="opacity" values="0.85;0.2;0.85" dur="2.7s" begin="0.3s" repeatCount="indefinite" />
        </circle>

        {/* Star sparkle — top right */}
        <path d="M468 48 L471 40 L474 48 L482 48 L476 53 L478.5 61 L471 56.5 L463.5 61 L466 53 L460 48 Z" fill="rgba(251,191,36,0.7)">
          <animate attributeName="opacity" values="0.7;0.15;0.7" dur="3.3s" repeatCount="indefinite" />
        </path>

        {/* Star sparkle — left side */}
        <path d="M26 188 L28.5 181 L31 188 L38 188 L32.5 192.5 L35 200 L28.5 195.5 L22 200 L24.5 192.5 L19 188 Z" fill="rgba(167,139,250,0.65)">
          <animate attributeName="opacity" values="0.65;0.1;0.65" dur="2.8s" begin="1.5s" repeatCount="indefinite" />
        </path>

        {/* Tiny dot — scattered */}
        <circle cx="54" cy="330" r="2.5" fill="rgba(244,114,182,0.6)">
          <animate attributeName="opacity" values="0.6;0.1;0.6" dur="2.1s" begin="0.8s" repeatCount="indefinite" />
        </circle>
        <circle cx="458" cy="58" r="2.5" fill="rgba(96,165,250,0.6)">
          <animate attributeName="opacity" values="0.6;0.1;0.6" dur="2.6s" begin="0.2s" repeatCount="indefinite" />
        </circle>
      </svg>
    </div>
  );
}

export default ThumbnailShowcase;
